version: 2

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & fmt
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform init -input=false
            terraform fmt && terraform plan -out=tfplan -var-file=variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply tfplan -input=false -var-file=variables.tfvars
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform destroy -input=false --auto-approve

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
      - hold-destroy:
          type: approval
          requires:
            - apply
      - destroy:
          requires:
            - hold-destroy
