version: 2

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform init -backend-config="token=${TF_API_TOKEN}"
            terraform fmt && terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .
  apply:
    steps:
      - attach_workspace:
        at: .
      - run:
          name: terraform fmt
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform apply
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker: [{ image: "circleci/python:latest" }]
    working_directory: "/tmp/project"
    steps:
      - run:
          name: "Push to S3"
          command: |
            pip install --user awscli
            export PATH="~/.local/bin:$PATH"
            git clone https://github.com/hashicorp/learn-terraform-circleci/ .
            pwd
            aws s3 sync --acl public-read "/home/circleci/project/assets" s3://${APP_BUCKET}
  destroy:
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform fmt
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform destroy --auto-approve
workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - plan
      - apply
      - deployment:
          requires:
            - apply
      - hold:
          type: approval
          requires:
            - deployment
      - destroy:
          requires:
            - hold
