version: 2

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform fmt and plan
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform init -backend-config="token=${TF_API_TOKEN}"
            terraform fmt && terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            terraform apply --auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker: [{ image: "circleci/python:latest" }]
    working_directory: "/tmp/project"
    steps:
      - run:
          name: "Push to S3"
          command: |
            pip install --user awscli
            export PATH="~/.local/bin:$PATH"
            git clone https://github.com/hashicorp/learn-terraform-circleci/ .
            pwd
            aws s3 sync --acl public-read "/tmp/project/assets" s3://${APP_BUCKET}

  destroy:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform destroy --auto-approve
workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan
      - apply:
          requires:
            - plan
      - deploy:
          requires:
            - apply
      - hold:
          type: approval
          requires:
            - deploy
      - destroy:
          requires:
            - hold
