version: 2

jobs:
  plan:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform fmt and plan
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform init -backend-config="token=${TF_API_TOKEN}"
            terraform fmt && terraform plan
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform apply
          command: |
            terraform apply --auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            terraform destroy --auto-approve

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan
      - hold-apply:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - hold-apply
      - hold-destroy:
          type: approval
          requires:
            - apply
      - destroy:
          requires:
            - hold-destroy
