version: 2

references:

base_image: &base_image
  hashicorp/terraform:light

working_directory: &working_directory
  /home/circleci/project

default_config: &default_config
  docker:
    - image: *base_image
  working_directory: *working_directory
  environment:
    BASH_ENV: /root/.bashrc
    TERRAFORM_ENV: /home/circleci/project/

repo_cache_key: &repo_cache_key
  v1-repo-{{ .Branch }}-{{ .Revision }}

terraform_init: &terraform_init
  run:
    name: terraform init
    command: |
      cd && touch $BASH_ENV
      source $BASH_ENV
      cd /home/circleci/project/
      terraform init -backend-config="token=${TF_API_TOKEN}"
  persist_to_workspace:
    root: /home/circleci/project
    paths:
      - /home/circleci/project


apply_job: &apply_job
  <<: *default_config
  steps:
    - *terraform_init

    - run:
        name: terraform apply
        command: |
          cd && touch $BASH_ENV
          source $BASH_ENV
          cd /home/circleci/project/
          terraform init -backend-config="token=${TF_API_TOKEN}"
          terraform apply --auto-approve
    - persist_to_workspace:
        root: /home/circleci/project
        paths:
          - /home/circleci/project

jobs:

  build:
    <<: *default_config
    steps:
      - checkout
      - run:
          name: terraform fmt
          command: |
            cd && touch $BASH_ENV
            source $BASH_ENV
            cd /home/circleci/project/
            terraform init -backend-config="token=${TF_API_TOKEN}"
            terraform fmt
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
          - /home/circleci/project

  plan:
    <<: *default_config
    steps:
      - *terraform_init
      - run:
          name: terraform plan
          command: |
            cd && touch $BASH_ENV
            source $BASH_ENV
            cd /home/circleci/project/
            terraform plan
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - /home/circleci/project


  apply:
    <<: *apply_job
  apply-with-approval:
    <<: *apply_job

  deployment:
    docker: [{ image: "circleci/python:latest" }]
    working_directory: "/home/circleci/project"

    steps:
      - run:
          name: "Push to S3"
          command: |
            pip install --user awscli
            export PATH="~/.local/bin:$PATH"
            git clone https://github.com/hashicorp/learn-terraform-circleci/ .
            pwd
            aws s3 sync --acl public-read "/home/circleci/project/assets" s3://${APP_BUCKET}


  destroy:
    <<: *default_config
    steps:
      - *terraform_init
      - run:
          name: "Destruction of env"
          command: |
            source $BASH_ENV
            cd /home/circleci/project/
            terraform destroy --auto-approve



workflows:
  version: 2
  build_plan_approve_apply:
    jobs:
      - build
      - plan:
          requires:
            - build
      - apply:
          requires:
            - plan
      - deployment:
          requires:
            - apply
      - hold:
          type: approval
          requires:
            - deployment
      - destroy:
          requires:
            - hold
