version: 2

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: terraform init & fmt
          command: |
            cd && touch /root/.bashrc
            source /root/.bashrc
            cd /tmp/project/
            terraform init -input=false
            terraform fmt && terraform plan -out tfapply -var-file variables.tfvars
            pwd
      - persist_to_workspace:
          root: .
          paths:
            - .

  apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform
          command: |
            terraform apply tfapply
      - persist_to_workspace:
          root: .
          paths:
            - .

  plan-destroy:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform create destroy plan
          command: |
            pwd
            terraform plan -destroy -out tfdestroy -var-file variables.tfvars

  destroy:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: terraform destroy
          command: |
            pwd
            terraform apply tfdestroy

workflows:
  version: 2
  plan_approve_apply:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          type: approval
          requires:
            - apply
      - destroy:
          requires:
            - plan-destroy
